### ISSUE TITLE
Do not call choco with --debug --verbose by default

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/puppet-chocolatey#100]
The output from error messages is way too much. It would be helpful to see only what has errored and allow the user to investigate further if need be. This gives the user the ability to choose whether or not to add those values to the arguments as part of `install_options` and `uninstall_options`.

**Comment by ferventcoder** [comment]
This was requested by someone at PuppetConf, although the name escapes me.

**Comment by msolonkovich26** [comment]
Hi Rob - @ferventcoder - I was the one requesting this. If I have some free time I can try to throw something together and present it to you for approval.

BTW: side note - not sure if you ever solved it or not but we started using monk-ee's inline_template to set our chocolatey.config file for us: https://github.com/monk-ee/inline_template

Just curious to see if you had a better way of doing this?

**Comment by ferventcoder** [comment]
@msolonkovich26 would love if you could put something together.

For monk-ee's inline template - I hadn't seen that before. Looks interesting. We are working on being able to set everything related to configuration through puppet-chocolatey. Until that is complete, if you find something that works, you should use that. :)

**Comment by ferventcoder** [comment]
This is going into 1.2.3 (releasing in a few minutes).
