### ISSUE TITLE
Error when using puppet apply (the serverversion fact is not present)

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [chocolatey/puppet-chocolatey#105]
In [manifests/init.pp:80](https://github.com/chocolatey/puppet-chocolatey/blob/64cc7ab1539665226eb704db2689d00c8eb406cd/manifests/init.pp#L80) the `$::serverversion` fact is used in a version comparison. This fact will not be available if `puppet apply` is used. This causes `undef` to be passed to `versioncmp`, which is an error. (Using `--strict_variables`, it will error about the missing variable).

A workaround:
```powershell
$env:FACTER_serverversion = '4.3.1'
& 'C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat' apply foobar
```

To fix this in chocolatey we could do something like:

```puppet
﻿if ( (getvar('::serverversion') and versioncmp(getvar('::serverversion'), '3.4.0') >= 0) ) or (versioncmp($::clientversion, '3.4.0') >= 0) {
# ...
```

**Comment by ferventcoder** [comment]
Does the OR not work?

`if (versioncmp($::serverversion, '3.4.0') >= 0) or (versioncmp($::clientversion, '3.4.0') >= 0)`

**Comment by ferventcoder** [comment]
I'm guessing because the version is undef it doesn't work. Perhaps we should rethink that section a bit to use `serverversion` if it is present, otherwise use `clientversion`?

**Comment by Joris-van-der-Wel** [comment]
`versioncmp` gives you an error because effectively it results in `versioncmp(undef, '3.4.0')` (assuming strict mode is disabled):

`Error while evaluating a Function Call, 'versioncmp' parameter 'a' expects a String value, got Undef`

**Comment by ferventcoder** [comment]
Yeah, that's pretty bad. I'm surprised I'm not seeing that fail in my specs? I'm guessing it is due to strict mode?

**Comment by Joris-van-der-Wel** [comment]
Odd... Try this:

```
C:\>"C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat" apply --version
4.3.1

C:\>"C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat" apply -e 'notice( versioncmp($::serverversion, "3.4.0") )'
Warning: Scope(Class[main]): Could not look up qualified variable '::serverversion';
Error: Evaluation Error: Error while evaluating a Function Call, 'versioncmp' parameter 'a' expects a String value, got Undef  at line 1:9 on node msvc-vm.local

C:\>"C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat" apply --strict_variables -e 'notice( versioncmp($::serverversion, "3.4.0") )'
Error: Evaluation Error: Unknown variable: '::serverversion'.  at line 1:20 on node msvc-vm.local
```

**Comment by ferventcoder** [comment]
Working on a fix now

**Comment by ferventcoder** [comment]
Actually that didn't work out quite like I wanted it to. Let me see what I can do. As a workaround, if you define a variable for serverversion, does that get things working again?

**Comment by Joris-van-der-Wel** [comment]
it only works if i add it as a fact, for example by using an environment variable called `FACTER_serverversion`. This is the workaround i am using right now.

Defining the variable in my site manifest did not work work. I guess this is because `$::serverversion` instead of `$serverversion` is used?

**Comment by empi89** [comment]
This issue should be fixed now?

**Comment by Joris-van-der-Wel** [comment]
Fixed for me on master (tested using 8f836503986165bec4999e1a211a44eea68985e7)

**Comment by empi89** [comment]
Thanks for your feedback. Could you please close this issue?

**Comment by ferventcoder** [comment]
Sometimes merging a PR doesn't actually close a ticket.

**Comment by ferventcoder** [comment]
Ah nevermind, the ticket didn't have this :/

**Comment by ferventcoder** [comment]
This is going live in a few minutes. Sorry about the delay

**Comment by Joris-van-der-Wel** [comment]
Thanks!
