### ISSUE TITLE
ensure => '[specificVersionNumber]' does not install package

### ISSUE THREAD

**Issue by chaim1221** [chocolatey/puppet-chocolatey#116]
Fresh install of PE2015.3 on Ubuntu 15.10
Windows 2012R2 agent

    package { 'notepadplusplus':
        ensure => '6.8.8',
        provider => 'chocolatey',
    }

does not install Notepad++ and does not give error; output 

> C:\> . $puppetCmd agent -t
> Info: Using configured environment 'production'
> Info: Retrieving pluginfacts
> Info: Retrieving plugin
> Info: Loading facts
> Info: Caching catalog for myComputer
> Info: Applying configuration version '1456355578'
> Notice: /Stage[main]/Profile::Baseline/Package[notepadplusplus]/ensure: created
> Notice: Applied catalog in 18.29 seconds

however, `ensure => installed` works as expected.

**Comment by ferventcoder** [comment]
Please go to the logs folder for choco and attach the install log from there as well.

**Comment by chaim1221** [comment]
Not working: https://gist.github.com/chaim1221/460dc6134f8b85dcaec4
Working: https://gist.github.com/chaim1221/8384ccd0ad6b78b5e15f

This time it said it used a cached copy of the installer, but it worked the second way even when it didn't have a cached copy. However that logfile is...well, huge.

**Comment by ferventcoder** [comment]
Well, that answers my question. You need to upgrade Chocolatey on those machines.

**Comment by chaim1221** [comment]
Gotcha. What's the minimum recommended version for `puppet-chocolatey`?

**Comment by ferventcoder** [comment]
@chaim1221 I mean you can use that one, but it's probably not going to work in all cases, as you are seeing. Why would you want the minimum recommended version?

**Comment by chaim1221** [comment]
We've had some problems with anything greater than 0.9.9.10 because it doesn't work well with our current CM system, which relies heavily on BoxStarter.

**Comment by ferventcoder** [comment]
@chaim1221 you will have the best experience with `puppet-chocolatey` if you upgrade to the latest available. Plus it will have the most security fixes.

Also @mwrock upgraded BoxStarter recently, so it should work fine with 0.9.9.0+.

**Comment by chaim1221** [comment]
Gotcha. I will give it another shot. Thanks for your help.

**Comment by ferventcoder** [comment]
Alternatively, if you need to roll back to 0.9.8 series, check out 0.9.8.33. If you find the 0.9.9 is missing some of the alternative sources (`cygwin`, `windowsfeature`, etc), you may want to try with the 0.9.10 betas to get those back.

**Comment by ferventcoder** [comment]
Clarifying, if you need to roll back to the 0.9.8 series, I suggest 0.9.8.33. You will still need to provide a pull request to get this functionality to work properly in that version.

**Comment by chaim1221** [comment]
Oh, cool. We don't use `cygwin` but we do use `windowsfeature` stuff, although I'm trying to move that to in-house MSIs we manage with DISM. Actually trying to move away from BoxStarter and towards Chef/Puppet CM, so chocolatey@latest will probably work for us going forward.

**Comment by ferventcoder** [comment]
@chaim1221 I think that BoxStarter still has implementations for Windows Features.

For Puppet, I would suggest the [puppetlabs/windows module pack](https://forge.puppetlabs.com/puppetlabs/windows), which includes a bunch of Windows modules, including the windowsfeature module -  https://forge.puppetlabs.com/puppetlabs/windows/dependencies.

You've probably already seen this - https://github.com/chocolatey/puppet-chocolatey_server?

**Comment by chaim1221** [comment]
Oh, sweet. No, I hadn't seen that, and if we adopt Puppet we will definitely need to set one of those up.
