### ISSUE TITLE
use_7zip default is false, not true. 

### ISSUE THREAD

**Issue by pimpolderman** [chocolatey/puppet-chocolatey#117]
In init.pp comments it states the following:

@param [Boolean] use_7zip Whether to use built-in shell or allow installer
 to download 7zip to extract `chocolatey.nupkg` during installation.
 Defaults to `true`.

But the default seems to be false:

params.pp:
class chocolatey::params {
  $use_7zip                 = false
 }

Consider fixing the documentation or the params.pp.

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/puppet-chocolatey/blob/8f836503986165bec4999e1a211a44eea68985e7/manifests/params.pp#L5

The default is false. I think we want it to be that way considering it makes a call out to the internet when it is true and that could be surprising for organizations who are attempting to use the provider completely internally. It's really only necessary to be true on machines like Server Core.

**Comment by ferventcoder** [comment]
We'll call it a documentation bug and fix the documentation.

**Comment by ferventcoder** [comment]
Thanks for noting that! Does this agree with your thoughts about how it should default?

**Comment by pimpolderman** [comment]
Fair point regarding downloading of 7zip from internet. We should leave it to false as default indeed. A documentation would be great! Thanks for the fast response :+1:
