### ISSUE TITLE
How to provide windows architecture parameter in puppet code ?

### ISSUE THREAD

**Issue by rammaram06** [chocolatey/puppet-chocolatey#123]
I would like to condition to install 32bit or 64bit package..in my code.Is it possible?

If so..could you pls provide an example?

**Comment by ferventcoder** [comment]
Perhaps more context - this is completely possible and documented in Chocolatey now, and is supported using install_options with the provider, so more context will help draw out what your needs are.

**Comment by ferventcoder** [comment]
`install_options => ['--forcex86'],` will get you the 32 bit architecture no matter what. For 64bit architecture, if the package supports it, it is automatic.

**Comment by ferventcoder** [comment]
Closing as this has gone stale with no response @rammaram06 if you have further questions or wish to clarify what you were/are looking for, please comment and we can get this reopened.
