### ISSUE TITLE
Package falsely reports successful install

### ISSUE THREAD

**Issue by tisbeok** [chocolatey/puppet-chocolatey#124]
I have a Puppet manifest that installs JRE via chocolatey. After a machine is provisioned and performs a Puppet run, chocolatey sees JRE as being installed, but it is not. The logs show that chocolatey performs the install, and I have confirmed that the normal files exist in ProgramData\chocolatey\lib\jre, but the installer doesn't seem to execute normally- Program Files\Java does not exist. However, if I run the install via chocolatey (directly from PowerShell), the install is normal. Also, if I call puppet manually from PowerShell before it can do it's first run in the background, Java installs normally.

I will attach the log from the false positive run, replacing our package feed server hostname with "FQDN." The uploader was not working when I submitted the ticket.

I have observed this with the following environments (all on Windows 2012r2 x64):
puppet-server 3.7.1, puppet agent 3.7.1, chocolatey 0.9.9.11, puppet-chocolatey module 1.2.1
puppet-server 3.7.1, puppet agent 3.7.1, chocolatey 0.9.9.12, puppet-chocolatey module 1.2.1
puppetserver 2.3.1, puppet agent 3.7.1, chocolatey 0.9.9.12, puppet-chocolatey module 1.2.1
puppetserver 2.3.1, puppet agent 3.8.7, chocolatey 0.9.9.12, puppet-chocolatey module 1.2.2

[choco_jre_log.txt](https://github.com/chocolatey/puppet-chocolatey/files/245480/choco_jre_log.txt)

**Comment by ferventcoder** [comment]
This is likely the same as https://github.com/chocolatey/choco/issues/198

**Comment by tisbeok** [comment]
It looks like that ticket is concerning prematurely aborted packages. In my case, I only see this behavior if I let Puppet complete it's first run in the background. I do not interrupt it, and I do not observe the issue if I run Puppet manually with puppet agent -t or install the package with choco install jre.

**Comment by ferventcoder** [comment]
That is correct. I was thinking more about what this may be.

**Comment by ferventcoder** [comment]
I'm wondering if the installer itself has issues - it appears to be reporting a success on install.

**Comment by tisbeok** [comment]
If so, it's not new- I have experienced this with several versions of the java installer.

**Comment by trekytech7** [comment]
I have also seen this issue, and tried contacting the maintainers for the jre8 chocolatey Nuget. I did not see the same issue with jre version7. The client system being installed on is Windows 7 enterprise 64bit. In the interests of time, I've been considering just staying with a javaruntime 7 version... for now ;)

I think running puppet master 3.7.0, puppet client 3.7.2, choco 0.9.9.6, and choco-puppet 0.5.2... (Hopefully I have time to update before the fall semester this year, lol)

**Comment by tisbeok** [comment]
Thanks for the additional info @trekytech7. @ferventcoder, it looks like you were right about this being an issue with the installer based on this additional info as well as the fact that I am getting the same behavior (Puppet falsely reports successful install) when using a file resource to copy the installer and an exec resource to install java. Closing this issue as it seems it's not a chocolatey problem.
