### ISSUE TITLE
Problems with ensuring proper version to be passed as parameter.

### ISSUE THREAD

**Issue by marcinbojko** [chocolatey/puppet-chocolatey#149]
When using ensure in form:

```yaml
package:
  ensure: 1.1.1
```

Chocolatey calls for: 

C:\ProgramData\chocolatey\bin\choco.exe upgrade package -version 1.1.1 -y

which gives us:

> Error: Could not update: Execution of 'C:\ProgramData\chocolatey\bin\choco.exe upgrade package -version 1.1.1 -y ' returned 3010: Plted in error (converted to warning):
>  Cannot bundle unregistered option '-e'.

and on every run gives notify:
> Notice: /Stage[main]/Win_manage/Package[package]/ensure: ensure changed '1.1.1' to ' 1.1.1'
When using manually:

C:\ProgramData\chocolatey\bin\choco.exe upgrade package --version 1.1.1 -y

Package passes properly.

The problem is with **-version** instead of **--version**

Chocolatey in 0.10.3 version.

**Comment by ferventcoder** [comment]
Are you using chocolatey/chocolatey or puppetlabs/chocolatey?

The actually error is 3010 - which means you need to pass `--ignore-package-exit-codes` in the install_options. Or if you use puppetlabs/chocolatey, that is already handled for you.

**Comment by marcinbojko** [comment]
Thanks @ferventcoder , so another argument for switching to puppetlabs/chocolatey.

**Comment by ferventcoder** [comment]
For now at least. 👍

**Comment by ferventcoder** [comment]
The ultimate plan is to have this one on the edge of new features, etc, but right now it is in need of playing catch up with the work that has went into the puppetlabs/chocolatey version.

**Comment by ferventcoder** [comment]
Let me know if it still has the secondary issue once you've flipped. Oh by the way, it is a drop in replacement. You won't need to change anything else.

**Comment by marcinbojko** [comment]
If switching to puppetlabs/chocolatey will do - I'll do if. If not, I'll add "--ignore-package-exit-codes" as resource defaults to never, ever, ever remember of it.

**Comment by ferventcoder** [comment]
@marcinbojko other handy things in the puppetlabs/chocolatey module:

* chocolateysource
* chocolateyconfig
* chocolateyfeature

**Comment by marcinbojko** [comment]
Yup. But I wrote this part earlier, for myself, using chocolatey/chocolatey. And it works. And changing a lots of hosts is a pain. And so on ;)

**Comment by ferventcoder** [comment]
Fair, I would have assumed you would update your master and let it sync down the changes for you automatically.

**Comment by ferventcoder** [comment]
No worries, glad we had options to move you forward without a switch over.

**Comment by marcinbojko** [comment]
That part is yet to be determined. Testing now.

**Comment by marcinbojko** [comment]
As usuall  @ferventcoder - what would I do without you and Chocolatey? ;)

> Debug: Executing: 'C:\ProgramData\chocolatey\bin\choco.exe upgrade powershell -version 5.1.14409.1005 -y  --ignore-package-exit-codes'
> Notice: /Stage[main]/Win_manage/Package[powershell]/ensure: ensure changed '5.0.10586.20161216' to '5.1.14409.1005'
