### ISSUE TITLE
[BUG] Passing parameters to chocolateyInstall.ps1

### ISSUE THREAD

**Issue by StuartWhelan** [chocolatey/puppet-chocolatey#15]
The package I am installing in an inhouse package; a windows service.

I need to pass some parameters to my install script.

The trouble is the only way I can see to do this is using the choco -params functionality, which I do not think is exposed by the puppet module in a way that I can use.

I tried to use install_options, but something (Not sure if it is puppet or the puppet-chocolatey module) is wrapping the install_options value in a quote if the install_options value contains a space.

To give a simplified example, if I try:

```
class document_upload_service{
	package{ 'DocumentUploadService':
		ensure		=> latest,
		provider		=> 'chocolatey',
		install_options	=> "-install",
		source		=> 'http://10.0.2.63:8081/artifactory/api/nuget/puppet-local',
		}
 }
```

then in my logs I see:

```
Debug: Executing 'C:\Chocolatey\chocolateyInstall\chocolatey.cmd update DocumentUploadService -install -source http://10.0.2.63:8081/artifactory/api/nuget/puppet-local'
```
But if I use:

```
		install_options	=> "-params -install",
```

I get

```
Debug: Executing 'C:\Chocolatey\chocolateyInstall\chocolatey.cmd update DocumentUploadService "-params -install" -source http://10.0.2.63:8081/artifactory/api/nuget/puppet-local'
```

Can we get a way to pass complex parameters without getting quoted?

**Comment by ferventcoder** [comment]
Closes with #49
