### ISSUE TITLE
allow downgrade should work

### ISSUE THREAD

**Issue by TerribleDev** [chocolatey/puppet-chocolatey#156]
Hi, when I want to ensure a specific older version of a package to be installed I get  `  Use --allow-downgrade or --force to attempt to upgrade to older versions`

Ideally because I am asserting a specific version of a package it should downgrade.

**Comment by ferventcoder** [comment]
This works now.

Just set the allow downgrade option in `install_options`

**Comment by ferventcoder** [comment]
IIRC we can have set a feature switch so that this is not required to be passed everytime. However this is not an issue with the provider, please followup at https://github.com/chocolatey/choco/issues/new 

HTH

**Comment by TerribleDev** [comment]
thanks @ferventcoder
