### ISSUE TITLE
Puppet agent don't apply my own chocolatey module

### ISSUE THREAD

**Issue by alejandrolidon** [chocolatey/puppet-chocolatey#160]
I created a module and the init.pp it looks like: 
class msoffice365 {
 package { 'office365homepremium' : 
    ensure => installed,
    provider => 'chocolatey',
}
it is at .../etc/modules/msoffice365/manifests/
But when i run the puppetagent it recognizes but don't install anything just finish with no errors. There is something that is missing? When i run the debug agent it only mentions the module at:
Debug: /Package[office365homepremium]: Provider chocolatey does not support features virtual_packages; not managing attribute allow_virtual.

**Comment by alejandrolidon** [comment]
It worked changin 'office365homepremium' for 'office365proplus'

**Comment by ferventcoder** [comment]
I am also hopeful you used puppetlabs/chocolatey as compared to this module
