### ISSUE TITLE
Hard coded 7z url defeats proxies

### ISSUE THREAD

**Issue by helge000** [chocolatey/puppet-chocolatey#162]
[`templates/InstallChocolatey.ps1.erb`](
https://github.com/chocolatey/puppet-chocolatey/blob/master/templates/InstallChocolatey.ps1.erb#L90) sets the 7z url to a static value. 

This defeats class installation as we can only later set up a proxy for chocolatey.

I see some options:
- We could add a new parameter pointing to 7z?
- Bundle 7z inside the choco.nuget package itself
- Add 7z to this repository

I would like to volunteer for a fix.

**Comment by ferventcoder** [comment]
Just FYI, use puppetlabs/chocolatey for now, not this repo.

**Comment by helge000** [comment]
Right, still confusing for me. Shall I open this in puppetlabs jira?

**Comment by ferventcoder** [comment]
Secondly, you should be able to not use the 7z at all.

**Comment by helge000** [comment]
I still have issues running the unzip in background with windows 10. But I think 7z is still a feature unless you plan to depreciate it..?

**Comment by ferventcoder** [comment]
No plans to deprecate. That's why I'm pointing you to puppetlabs/chocolatey. Where someone (maybe you), provided a built-in PowerShell v5 way of uncompressing.

**Comment by ferventcoder** [comment]
Definitely on board for having a local 7z file that could be used.

**Comment by helge000** [comment]
@ferventcoder , I opend a new bug in [puppetlabs-jira](https://tickets.puppetlabs.com/browse/MODULES-6652) and will submit the PR over in in puppetlabs-chocolatey repo. Therefore I close this issue.

**Comment by ferventcoder** [comment]
MODULES-6652 / https://github.com/puppetlabs/puppetlabs-chocolatey/pull/94
