### ISSUE TITLE
[BUG] The OS handle's position is not what FileStream expected. Do not use a handle simultaneously in one FileStream and in Win32 code or another FileStream. This may cause data loss.

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/puppet-chocolatey#18]
I thought someone had already mentioned this issue before?

**Comment by rismoney** [comment]
Are all powershell executions from puppet plagued by this if they do any stderr writing and puppet writes to its tmp?  ie exec or other providers calling cmdlets, etc?

Does these need to be reraised on cmsonnect or attention brought to some folks with influence at msft?

**Comment by ferventcoder** [comment]
All posh if it redirects output to a file and writes to more than one
stream. As far as I know it affects up to v4.

On Thursday, January 8, 2015, Rich Siegel <notifications@github.com> wrote:

> Are all powershell executions from puppet plagued by this if they do any
> stderr writing and puppet writes to its tmp? ie exec or other providers
> calling cmdlets, etc?
>
> Does these need to be reraised on cmsonnect or attention brought to some
> folks with influence at msft?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/puppet-chocolatey/issues/18#issuecomment-69284433>
> .
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by vix633** [comment]
Definitely also running into this while running puppet -> boxstarter - > chocolatey

**Comment by ferventcoder** [comment]
This will close with #49

**Comment by rismoney** [comment]
interestingly, I commented the write-host commands in the template here (InstallChocolatey.ps1.erb) and the errors went away on my clean win2008r2 box.  PS 2.0.  .net 4.0

note - i had no issues on 2012r2, or win2008r2 with .net 4.5 and wmf 4.0

I still have 1 more error later on.  I think it comes from here-ish
https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/commands/ChocolateyUnpackSelfCommand.cs#L88
```
Notice: /Stage[protozoic]/Chocolatey::Install/Exec[install_chocolatey_official]/returns: Chocolatey is unpacking require
d files for use. Overwriting? True
Notice: /Stage[protozoic]/Chocolatey::Install/Exec[install_chocolatey_official]/returns: The OS handle's position is not
 what FileStream expected. Do not use a handle simultaneously in one FileStream and in Win32 code or another FileStream.
 This may cause data loss.
Notice: /Stage[protozoic]/Chocolatey::Install/Exec[install_chocolatey_official]/returns: out-lineoutput : The OS handle'
s position is not what FileStream expected. Do not use a handle simultaneously in one Fi
Notice: /Stage[protozoic]/Chocolatey::Install/Exec[install_chocolatey_official]/returns: leStream and in Win32 code or a
nother FileStream. This may cause data loss.
Notice: /Stage[protozoic]/Chocolatey::Install/Exec[install_chocolatey_official]/returns:     + CategoryInfo          : N
otSpecified: (:) [out-lineoutput], IOException
Notice: /Stage[protozoic]/Chocolatey::Install/Exec[install_chocolatey_official]/returns:     + FullyQualifiedErrorId : S
ystem.IO.IOException,Microsoft.PowerShell.Commands.OutLineOutputCommand
Notice: /Stage[protozoic]/Chocolatey::Install/Exec[install_chocolatey_official]/returns:
Notice: /Stage[protozoic]/Chocolatey::Install/Exec[install_chocolatey_official]/returns: executed successfully

```
