### ISSUE TITLE
Powershell Script in chocolatey package not working with puppet agent

### ISSUE THREAD

**Issue by gobins** [chocolatey/puppet-chocolatey#25]
I have included a script inside "chocolateyinstall.ps1" which runs at the time of installation of the package. The package installs fine when I run it locally but does not work with puppet. The modules that I'm using in the "chocolateyinstall.ps1" are not available on the 32 bit command. 

The problem maybe because chocolatey package provider is running on the 32 bit command.

**Comment by levilovelock** [comment]
What's going on with this? I have a problem I install hg with different versions of chocolatey and with or without puppet. All installed on windows 2008r2, 64 bit os/cpu

v0.9.8.23 - installs 64 bit version
v0.9.8.31 - installs 64 bit version

v0.9.8.23 via puppet - installs 64 bit version
v0.9.8.31 via puppet - installs 32 bit version!!!!

I saw this patch get released in v0.9.8.24 https://github.com/chocolatey/chocolatey/pull/396/files and was wondering if it could have anything to do with it. I'm using the rismoney/chocolatey module. I also ran the new code for the bits (from PR396) in a ps script through puppet and just plain powershell, both output the bits to be 64, so really dunno what's going on here.

Anyone have an idea?

**Comment by ferventcoder** [comment]
This issue is still likely a problem if you are on the 32-bit version of puppet. Now that we have a provider that no longer uses powershell, we may still need to resolve the issue. However it seems more like we need to ensure we use a 64-bit prompt to call chocolatey.

**Comment by ferventcoder** [comment]
Choco now will automatically start searching for powershell in sysnative first, so it will automatically resolve to the 64-bit version of powershell.

**Comment by ferventcoder** [comment]
That was present in 0.9.9.x series. I just realized, so things should be good to go now.
