### ISSUE TITLE
Make it clear that chocolatey needs to be installed on the node

### ISSUE THREAD

**Issue by JasonCrease** [chocolatey/puppet-chocolatey#26]
If you don't install chocolatey on the node first, you get a not very helpful: 'Provider chocolatey is not functional' error. I assumed that the provider 'just worked'. I ended up using:

  exec { 'install-chocolatey':
    command  => "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))",
    provider => powershell,
  }

**Comment by arcotek-ltd** [comment]
> in site.pp i set a default also, to avoid putting a provider parameter on every package either...
> 
> ```
> if $::kernel == Windows {
>   Package { provider => chocolatey }
> }
> ```

@rismoney, should this install chocolatey, or do I still need use `exec` as @JasonCrease suggests in his opening statement?

Thanks

**Comment by rismoney** [comment]
No that does not install chocolatey.  That stanza simply instructs puppet to use chocolatey as it's default package provider conditionally on Windows.  By putting it in site.pp provides a global scope.

ref:
https://puppet.com/docs/puppet/6.4/lang_defaults.html
