### ISSUE TITLE
Change version to latest

### ISSUE THREAD

**Issue by onzyone** [chocolatey/puppet-chocolatey#42]
Hello There,

I have been working on developing a pe-agent upgrader. One thing that I noticed was chocolaty would do an upgrade when I ran the puppet agent in debug. So testing it out with just chocolatey: 

```
C:\ProgramData\chocolatey\chocolateyInstall\chocolatey.cmd update pe-agent -source nuget-repo

Nothing to update.
```

So to test that my nuget package was right, I ran an install vs upgrade and it works as planned, with one lingering affect, puppet tries to change 3.3.2 to latest all the time (this I can likely fix in the puppet manifest with a version number vs latest)

```
Debug: Executing 'C:\ProgramData\chocolatey\chocolateyInstall\chocolatey.cmd upd
ate pe-agent  -source nuget-repo'
Notice: /Stage[main]/Puppet_enterprise_agent_upgrade/Package[pe-agent]/ensure: e
nsure changed '3.3.2' to 'latest'
Debug: /Package[pe-agent]: The container Class[Puppet_enterprise_agent_upgrade]
will propagate my refresh event
```

Full details can be found on this google groups forum:
https://groups.google.com/forum/#!topic/puppet-users/SKCmygyNTnA

Thanks
Jason.

**Comment by ferventcoder** [comment]
@onzyone is your issue resolved?

**Comment by onzyone** [comment]
Yes ...
