### ISSUE TITLE
check for installed packages is case sensitive

### ISSUE THREAD

**Issue by wjrogers** [chocolatey/puppet-chocolatey#43]
The provider method that parses chocolatey output for the list of installed packages uses case sensitive string matching. Chocolatey, like most of Windows, is not case sensitive. This can lead to a situation where the provider appears to work (the package gets installed), but it can't tell that the package is installed, so it tries to install it again every run, delaying the puppet agent run by a long time. This may also be the root cause of the apparently spurious messages discussed in issue #36.

I think the provider's check for installed packages should be case *in*sensitive for ease of use and reliability, especially because the correct case for packages names is somewhat obscure when browsing packages on chocolatey.org.

**Comment by ferventcoder** [comment]
This will close with #49
