### ISSUE TITLE
Error trying to find some path when running Puppet Apply

### ISSUE THREAD

**Issue by lmayorga1980** [chocolatey/puppet-chocolatey#57]
**Puppet Version** : 4.0
**Puppet Chocolatey Module Version**: 0.4.1
**Chocolatey Version**: 0.9.9.5

I believe chocolatey.cmd was removed from the latest version of chocolatey and the module chocolatey for puppet needs to point to the right path

```
Debug: Puppet::Type::Package::ProviderChocolatey: file C:\ProgramData\chocolatey\chocolateyInstall\chocolatey.cmd does not exist
```

**Comment by ferventcoder** [comment]
@lmayorga1980 let me get you going really quickly - https://forge.puppetlabs.com/chocolatey/chocolatey
