### ISSUE TITLE
`choco list` will become local only

### ISSUE THREAD

**Issue by alexchandel** [chocolatey/puppet-chocolatey#68]
Per [choco#158](https://github.com/chocolatey/choco/issues/158), `choco list` may default to local only in the future. `choco search` should be used instead to list all packages, including those not installed.

**Comment by ferventcoder** [comment]
I fail to understand what #158 has to do with the list used here - list local only is entirely what this provider would ever use.

**Comment by ferventcoder** [comment]
Closing as invalid.

**Comment by alexchandel** [comment]
Sorry, overly broad search parameters!
