### ISSUE TITLE
Error example to set default provider in README

### ISSUE THREAD

**Issue by evilhamsterman** [chocolatey/puppet-chocolatey#69]
There is a small syntactical error in the README on how to set the default provider to chocolatey.

There should be a second set of brackets around the Package line so this 

```puppet
case $operatingsystem {
  'windows':
    Package { provider => chocolatey, }
}
```

should be this

```puppet
case $operatingsystem {
  'windows': {
    Package { provider => chocolatey, }
  }
}
```

Otherwise you get a syntax error.

**Comment by MorbosVermin** [comment]
Second - I hit this issue to using Puppet 4.5 and latest version of this module.

**Comment by ferventcoder** [comment]
Ah, thanks! We should get that corrected in the readme.

**Comment by ferventcoder** [comment]
Corrected in the readme!

**Comment by ferventcoder** [comment]
I'm not sure how I missed the original notification on this...
