### ISSUE TITLE
Package ensure => $version, should use upgrade rather than install if a version is already installed

### ISSUE THREAD

**Issue by steve-hawkins** [chocolatey/puppet-chocolatey#71]
When stating a specific version of a package ```choco.exe list -lo -r``` should be used to determine if the package is already present, if present ```choco.exe upgrade $package -version $version -dvy``` else ```choco.exe install $package -version $version -dvy```

output of ```puppet agent -t --debug```

```
Debug: Prefetching chocolatey resources for package
Debug: Executing 'C:\ProgramData\chocolatey\bin\choco.exe -v'
Debug: Executing 'C:\ProgramData\chocolatey\bin\choco.exe list -lo -r'
Debug: Executing 'C:\ProgramData\chocolatey\bin\choco.exe install win-pack-man -version 0.0.13 -dvy '
Notice: /Stage[main]/Win_pack_man/Package[win-pack-man]/ensure: ensure changed '0.0.9' to '0.0.13'
```

At the moment ```choco.exe install``` is being used even if the package is already present, which is leading to strange behavior in the c:/programdata/chocolatey/lib directory, such as duplicate content.

```choco.exe -v 0.9.9.6```

output of ```puppet module list```

```
/etc/puppetlabs/puppet/environments/production/modules
└── counsyl-windows (v1.0.0)
/etc/puppetlabs/puppet/modules
├── badgerious-windows_env (v2.2.1)
├── choco_inst (???)
├── chocolatey-chocolatey (v1.0.1)
├── counsyl-sys (v0.9.18)
├── hiscox-app_obx (v0.0.1)
├── jordan-windows_service (v0.0.4)
├── opentable-iis (v1.3.0)
├── programs_dotnet45 (???)
├── programs_wmf40 (???)
├── puppet-windowsfeature (v1.1.0)
├── puppetlabs-acl (v1.0.3)
├── puppetlabs-dism (v1.1.0)
├── puppetlabs-powershell (v1.0.4)
├── puppetlabs-registry (v1.1.0)
└── win_pack_man (???)
```

**Comment by ferventcoder** [comment]
Definitely a bug.

**Comment by ferventcoder** [comment]
Found out why - https://github.com/puppetlabs/puppet/blob/master/lib/puppet/type/package.rb#L118-L130

**Comment by ferventcoder** [comment]
Think this is as easy as moving to upgrade instead of install.

**Comment by ferventcoder** [comment]
Of course I had to make reservations for install with packages.config - not allowed with upgrade/uninstall.

**Comment by ferventcoder** [comment]
@steve-hawkins take a look at https://github.com/chocolatey/puppet-chocolatey/pull/73

**Comment by ferventcoder** [comment]
@steve-hawkins this has been released in [1.0.2](https://forge.puppetlabs.com/chocolatey/chocolatey/1.0.2)

**Comment by steve-hawkins** [comment]
Thanks Rob!

Excellent turn-around and I can confirm this has sorted the original issue.

I have however found that this does not support down-grading versions and raised a new issue https://github.com/chocolatey/puppet-chocolatey/issues/75

**Comment by ferventcoder** [comment]
FYI just implemented an additional fix here so I could implement held.
