### ISSUE TITLE
Package ensure => $version, does not support down-grading versions

### ISSUE THREAD

**Issue by steve-hawkins** [chocolatey/puppet-chocolatey#75]
When stating a specific version of a package the provider should be able to determine if the package already exists and if the present package version is higher than the specified version, the present package is uninstalled and specified version is installed.

output of ```puppet agent -t --debug```

```
Debug: Prefetching chocolatey resources for package
Debug: Executing 'C:\ProgramData\chocolatey\bin\choco.exe -v'
Debug: Executing 'C:\ProgramData\chocolatey\bin\choco.exe list -lo -r'
Debug: Executing 'C:\ProgramData\chocolatey\bin\choco.exe upgrade --noop chocolatey -r'
Debug: Class[Choco_inst]: The container Stage[main] will propagate my refresh event
Debug: Executing 'C:\ProgramData\chocolatey\bin\choco.exe upgrade win-pack-man -version 0.0.9 -dvy '
Notice: /Stage[main]/Win_pack_man/Package[win-pack-man]/ensure: ensure changed '0.0.13' to '0.0.9'
```

At the moment this results in present version remains and the specified version is ignored.

```choco.exe -v 0.9.9.8```

output of ```puppet module list```

```
/etc/puppetlabs/puppet/environments/production/modules
└── counsyl-windows (v1.0.0)
/etc/puppetlabs/puppet/modules
├── badgerious-windows_env (v2.2.1)
├── choco_inst (???)
├── chocolatey-chocolatey (v1.0.2)
├── counsyl-sys (v0.9.18)
├── hiscox-app_obx (v0.0.1)
├── jordan-windows_service (v0.0.4)
├── opentable-iis (v1.3.0)
├── programs_dotnet45 (???)
├── programs_wmf40 (???)
├── puppet-windowsfeature (v1.1.0)
├── puppetlabs-acl (v1.0.3)
├── puppetlabs-dism (v1.1.0)
├── puppetlabs-powershell (v1.0.4)
├── puppetlabs-registry (v1.1.0)
└── win_pack_man (???)
```

**Comment by ferventcoder** [comment]
Choco itself doesn't support downgrading versions. The current way to do that is to uninstall and then reinstall or use `--force` to install the version you want.

**Comment by ferventcoder** [comment]
However `--force` will cause it to run every time, so it's probably not what you are looking for either.

**Comment by steve-hawkins** [comment]
Yeah, I have been wondering where this logic should be located.

We should generally be moving forward rather than back, but there could be a requirement to move back. I guess we could go down the route of building from bare metal on every deployment which would negate this as an issue, but I just don't like the way Puppet is telling me it has successfully moved from 0.0.13 to 0.0.9 when it has actually failed.

**Comment by ferventcoder** [comment]
> I just don't like the way Puppet is telling me it has successfully moved from 0.0.13 to 0.0.9 when it has actually failed.

Yeah, I think we need to handle that. Or return a better message when the version is newer.

**Comment by ferventcoder** [comment]
Actually I think the proper thing to do is make chocolatey fail - then that can bubble up. I filed https://github.com/chocolatey/choco/issues/365 to handle this scenario.

**Comment by ferventcoder** [comment]
I think this issue closes?

**Comment by TerribleDev** [comment]
@ferventcoder honestly, it would be nice if there was a property in the puppet package declaration that allowed for downgrades

like 

``` pp
    package { 'terraform':
        ensure   => '0.7.3',
        provider => 'chocolatey'
        allow_downgrade => true
    }

```

**Comment by ferventcoder** [comment]
@TerribleDev we are using the package resource, which means that would then be there for all package types. That is why puppet has `install_options`, to allow for switches and arguments to be passed that are specific to the underlying package manager. This is actually done because Chocolatey has supported it since 0.9.9.9.
