### ISSUE TITLE
Folder paths for chocolatey in windows_base.pp should be set correctly

### ISSUE THREAD

**Issue by dragan-stepanovic-devtech** [chocolatey/puppet-chocolatey#78]
Installation of chocolatey for master machine was not successful since, I guess, the paths in
Install Packages with Chocolatey section of 
modules\atomia\manifests\windows_base.pp
are not set correctly.

Specifically,
  # Install Packages with Chocolatey
  exec { 'install-chocolatey':
    command => "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))",
    provider  => powershell,
    onlyif  => 'Test-Path C:\Chocolatey'
  }
  
  exec { 'set-chocolatey-path':
    command => 'c:\windows\system32\cmd.exe /c SET PATH=%PATH%;%systemdrive%\chocolatey\bin',
    creates => "c:/install/chocolatey_installed.txt",
    require  => Exec['install-chocolatey'],
  }

Actual paths are:
C:\ProgramData\chocolatey for 'install-chocolatey' and
path C:\ProgramData\chocolatey\bin for 'set-chocolatey-path'

**Comment by ferventcoder** [comment]
What are you asking for here? This module doesn't have a windows_base.pp, nor does it yet provide the ability to install Chocolatey, see #76 for how we will offer the install of Chocolatey.

**Comment by ferventcoder** [comment]
> modules\atomia\manifests\windows_base.pp

This should help you find where you need to follow up.

**Comment by dragan-stepanovic-devtech** [comment]
Sorry, I've missed the repository...
